import type { StyleLibraryLifecycleState } from "./types";

export const PROMOTE_TARGET_LIFECYCLE: StyleLibraryLifecycleState = "user_selectable";

export const PROMOTE_MIN_LIFECYCLE: StyleLibraryLifecycleState = "paste_qa_pass";

export const PROMOTE_PROPOSAL_STORY = "S9-STORY-007";

export const PROMOTE_DEFAULT_ELIGIBLE_DECISION =
  "default_eligible requires separate PO decision";

export const PROMOTE_BLOCK_REASON_CODES = {
  NOT_VARIANT_ASSET: "NOT_VARIANT_ASSET",
  LIFECYCLE_TOO_LOW: "LIFECYCLE_TOO_LOW",
  ALREADY_USER_SELECTABLE: "ALREADY_USER_SELECTABLE",
  ALREADY_DEFAULT_ELIGIBLE: "ALREADY_DEFAULT_ELIGIBLE",
  ALREADY_RELEASE1_REQUIRED: "ALREADY_RELEASE1_REQUIRED",
  VALIDATOR_FAIL: "VALIDATOR_FAIL",
  BLOCKING_ISSUES: "BLOCKING_ISSUES",
  MISSING_PASTE_QA_EVIDENCE: "MISSING_PASTE_QA_EVIDENCE",
  MISSING_EVIDENCE_REFS: "MISSING_EVIDENCE_REFS",
  MISSING_RUNTIME_VARIANT_ID: "MISSING_RUNTIME_VARIANT_ID",
  DEPRECATED: "DEPRECATED",
  COMPATIBILITY_WARNING: "COMPATIBILITY_WARNING",
} as const;

export type PromoteBlockReasonCode =
  (typeof PROMOTE_BLOCK_REASON_CODES)[keyof typeof PROMOTE_BLOCK_REASON_CODES];

export const PROMOTE_PROPOSED_PATCH_PRESET_ID = "miaopian-classic";
