export type {
  BlockTypeMismatchFallbackAction,
  ColorTokenRef,
  CompatibilityIssue,
  CopySafety,
  CssCompatibilityLevel,
  CssCompatibilityResult,
  Density,
  FallbackPolicy,
  FallbackVariantPolicy,
  ForbiddenCssFallbackAction,
  ForbiddenCssPolicyAction,
  InlineMarkColorInput,
  MissingVariantFallbackAction,
  PresetDefinition,
  ResolveArticleStyleOptions,
  ResolvedArticleStyle,
  ResolvedBlockStyle,
  ResolvedStyleSource,
  ResolvedStyleTokens,
  RiskyCssFallbackAction,
  RiskyCssPolicyAction,
  StyleRegistry,
  StyleResolveContext,
  StyleResolveIssue,
  StyleSchemaVersion,
  StyleValidationIssue,
  StyleValidationResult,
  StyleValidationSeverity,
  ThemeDefinition,
  ThemeTokenMap,
  ThemeTokens,
  TitleBlockLayoutCompatibility,
  TitleBlockLayoutCompatibilityTable,
  TitleBlockLayoutMode,
  TitleBlockLayoutRiskLevel,
  ValidateResolvedArticleStyleContext,
  ValidateStyleRegistryOptions,
  ValidateTitleBlockLayoutOptions,
  ValidateVariantDefinitionContext,
  VariantCompatibility,
  VariantComponentProtocol,
  VariantDefinition,
  VariantSlotDefinition,
  VariantStatus,
  VariantWeChatCompatibility,
  WeChatCompatibilityCheckResult,
  WeChatCompatibilityProfile,
  WeChatCompatibilityTarget,
  WeChatCssRules,
} from "./types";

export {
  COLOR_TOKEN_REFS,
  STYLE_SCHEMA_VERSION,
  isColorTokenRef,
  isLegacyRawColor,
  normalizeColorTokenRef,
} from "./tokens";

export {
  TITLE_BLOCK_COMPONENT_ID,
  TITLE_BLOCK_LAYOUT_MODES,
} from "./types";

export {
  blockTypeMismatchFallbackActionSchema,
  colorTokenRefSchema,
  copySafetySchema,
  densitySchema,
  fallbackPolicySchema,
  fallbackVariantPolicySchema,
  forbiddenCssFallbackActionSchema,
  forbiddenCssPolicyActionSchema,
  inlineMarkColorInputSchema,
  missingVariantFallbackActionSchema,
  presetDefinitionSchema,
  riskyCssFallbackActionSchema,
  riskyCssPolicyActionSchema,
  styleRegistrySchema,
  styleSchemaVersionSchema,
  styleValidationIssueSchema,
  styleValidationResultSchema,
  styleValidationSeveritySchema,
  themeDefinitionSchema,
  themeTokensSchema,
  titleBlockLayoutCompatibilitySchema,
  titleBlockLayoutCompatibilityTableSchema,
  titleBlockLayoutModeSchema,
  titleBlockLayoutRiskLevelSchema,
  variantCompatibilitySchema,
  variantComponentProtocolSchema,
  variantDefinitionSchema,
  variantSlotDefinitionSchema,
  variantStatusSchema,
  variantWeChatCompatibilitySchema,
  weChatCompatibilityProfileSchema,
  weChatCompatibilityTargetSchema,
  weChatCssRulesSchema,
} from "./schemas";

export type {
  PresetDefinitionInput,
  StyleRegistryInput,
  ThemeDefinitionInput,
  VariantDefinitionInput,
  WeChatCompatibilityProfileInput,
} from "./schemas";

export {
  StyleRegistryError,
  getPresetById,
  getThemeById,
  getVariantById,
  getVariantsForBlockType,
  parseStyleRegistry,
  validateStyleRegistrySchema,
} from "./registry";

export {
  StyleResolveError,
  resolveArticleStyle,
  resolveBlockStyle,
} from "./resolver";

export {
  WECHAT_MP_COMPATIBILITY_PROFILE,
  parseWeChatCompatibilityProfile,
  validateCssDeclarationCompatibility,
  validateCssPropertyCompatibility,
  validateVariantWechatCompatibility,
} from "./compatibility";

export {
  RELEASE1_FALLBACK_VARIANT_POLICY,
  buildStyleValidationResult,
  normalizeCopySafetyInput,
  parseFallbackVariantPolicy,
  parseStyleValidationResult,
  validateResolvedArticleStyle,
  validateStyleRegistry,
  validateVariantDefinition,
  validateVariantForWechatCopy,
} from "./validation";

export {
  TITLE_BLOCK_LAYOUT_COMPATIBILITY_TABLE,
  assertTitleBlockLayoutTableComplete,
  getFallbackTitleBlockLayoutMode,
  getTitleBlockLayoutCompatibility,
  isTitleBlockLayoutAllowedForCopy,
  isTitleBlockVariant,
  validateTitleBlockLayoutCompatibility,
} from "./title-layout";
